on: [ workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
      - uses: actions/upload-artifact@v2
        with:
          name: fatjars
          path: ./**/target/leaderboard*fat.jar
          retention-days: 2
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: fatjars
      - name: Display structure of downloaded files
        run: ls -R
