on: [ workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
